// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsAPI from "./wailsapi.js";
import * as WailsFileService from "./wailsfileservice.js";
export {
    WailsAPI,
    WailsFileService
};
