// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsAPI wraps controller.AppController and implements api.SpreadsheetAPI.
 * Exposed to frontend via Wails service binding - methods callable via window.wails.Call.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "./api/models.js";

/**
 * DeleteCell removes a cell's contents.
 * @param {number} row
 * @param {number} col
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function DeleteCell(row, col) {
    return $Call.ByID(2822046665, row, col).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExportCSV exports the spreadsheet to CSV format. Stub for Epic 5.
 * @param {string} path
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function ExportCSV(path) {
    return $Call.ByID(2787608772, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAllCells retrieves all non-empty cells for rendering.
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function GetAllCells() {
    return $Call.ByID(1978660854).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCellFormula retrieves a cell's formula (if any).
 * @param {number} row
 * @param {number} col
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function GetCellFormula(row, col) {
    return $Call.ByID(671338660, row, col).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCellRef returns the cell reference (e.g., "A1") for the given row and column.
 * @param {number} row
 * @param {number} col
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function GetCellRef(row, col) {
    return $Call.ByID(3838439339, row, col).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCellValue retrieves a cell's value and computed result.
 * @param {number} row
 * @param {number} col
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function GetCellValue(row, col) {
    return $Call.ByID(2722886219, row, col).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetFileStatus retrieves the current file status.
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function GetFileStatus() {
    return $Call.ByID(2744062494).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * HasUnsavedChanges returns true if there are unsaved changes.
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function HasUnsavedChanges() {
    return $Call.ByID(388144661).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ImportCSV imports data from a CSV file. Stub for Epic 5.
 * @param {string} path
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function ImportCSV(path) {
    return $Call.ByID(1546106325, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LoadFile loads a .sheet file from disk (path provided by caller).
 * @param {string} path
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function LoadFile(path) {
    return $Call.ByID(2055527152, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * NewSpreadsheet creates a new empty spreadsheet.
 * Clears all cells, resets file status to "Untitled - Unsaved", clears file path, sets modified=false.
 * If there are unsaved changes, shows Save/Don't Save/Cancel dialog first.
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function NewSpreadsheet() {
    return $Call.ByID(2472652690).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenFile shows native Open dialog, reads file via FileService, loads spreadsheet.
 * Returns early with success if user cancels dialog.
 * If there are unsaved changes, shows Save/Don't Save/Cancel dialog first.
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function OpenFile() {
    return $Call.ByID(1147815984).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveAs shows Save dialog and saves to the chosen path.
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function SaveAs() {
    return $Call.ByID(3517471551).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveFile saves the spreadsheet to disk.
 * When path is empty: uses current file path or shows Save dialog if none.
 * @param {string} path
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function SaveFile(path) {
    return $Call.ByID(2468800941, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetCellValue sets a cell's value or formula.
 * @param {number} row
 * @param {number} col
 * @param {string} value
 * @returns {$CancellablePromise<api$0.Response>}
 */
export function SetCellValue(row, col, value) {
    return $Call.ByID(4267485671, row, col, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = api$0.Response.createFrom;
