// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCells() {
  return window['go']['main']['App']['GetAllCells']();
}

export function GetCellRawValue(arg1, arg2) {
  return window['go']['main']['App']['GetCellRawValue'](arg1, arg2);
}

export function GetCellRef(arg1, arg2) {
  return window['go']['main']['App']['GetCellRef'](arg1, arg2);
}

export function GetCellValue(arg1, arg2) {
  return window['go']['main']['App']['GetCellValue'](arg1, arg2);
}

export function SetCellValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCellValue'](arg1, arg2, arg3);
}
