// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCells():Promise<Record<string, string>>;

export function GetCellRawValue(arg1:number,arg2:number):Promise<string>;

export function GetCellRef(arg1:number,arg2:number):Promise<string>;

export function GetCellValue(arg1:number,arg2:number):Promise<string>;

export function SetCellValue(arg1:number,arg2:number,arg3:string):Promise<void>;
