// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Response represents a standardized API response for all spreadsheet operations.
 * It provides consistent success/failure indication, optional data payloads,
 * and structured error information with error codes for testing.
 * 
 * Usage patterns:
 * 
 * 	Success with data: Response{Success: true, Data: cellValue}
 * 	Success without data: Response{Success: true}
 * 	Error with code: Response{Success: false, Error: "message", Code: CIRCULAR_REF}
 */
export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * Success indicates whether the operation completed successfully.
             * true = operation succeeded, false = operation failed
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Data contains the optional response payload.
             * The type depends on the API method:
             *   - GetCellValue: map with "value" and "computed" fields
             *   - GetAllCells: array of cell objects
             *   - GetFileStatus: map with "path", "saved", "modified" fields
             * @member
             * @type {any | undefined}
             */
            this["data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Error contains a human-readable error message when Success is false.
             * Should be clear and actionable for users (NFR-U4).
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Code contains a machine-readable error code for testing and UI logic.
             * Use the error code constants defined below.
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}
